# Generated by Django 2.0.7 on 2019-12-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('newsId', models.AutoField(primary_key=True, serialize=False)),
                ('newsTitle', models.CharField(max_length=300)),
                ('newsImg', models.URLField(null='True')),
            ],
            options={
                'db_table': 'Test29',
            },
        ),
    ]
