# Generated by Django 2.0.7 on 2019-12-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test29', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='newsURL',
            field=models.URLField(max_length=300, null='True'),
        ),
    ]
