# Generated by Django 2.0.7 on 2019-12-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('Id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=500, null='True')),
                ('Img', models.URLField(null='True')),
                ('BuyUrl', models.URLField(null='True')),
                ('Date', models.CharField(max_length=50)),
                ('Hour', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ArhDrama',
            },
        ),
    ]
